In [0]:
import tensorflow as tf
import numpy as np
import pandas as pd
import tempfile
from sklearn.model_selection import train_test_split

In [11]:
data = pd.DataFrame(pd.read_csv("Car_Data.csv"))
data.head(100)

   buying  maint  doors persons lug_boot safety rating
0   vhigh  vhigh      2       2    small    low  unacc
1   vhigh  vhigh      2       2    small    med  unacc
2   vhigh  vhigh      2       2    small   high  unacc
3   vhigh  vhigh      2       2      med    low  unacc
4   vhigh  vhigh      2       2      med    med  unacc
..    ...    ...    ...     ...      ...    ...    ...
95  vhigh  vhigh  5more       4      med   high  unacc
96  vhigh  vhigh  5more       4      big    low  unacc
97  vhigh  vhigh  5more       4      big    med  unacc
98  vhigh  vhigh  5more       4      big   high  unacc
99  vhigh  vhigh  5more    more    small    low  unacc

[100 rows x 7 columns]

In [12]:
print('buying data is : ' , data['buying'].unique())
print('maint data is : ' , data['maint'].unique())
print('doors data is : ' , data['doors'].unique())
print('persons data is : ' , data['persons'].unique())
print('lug_boot data is : ' , data['lug_boot'].unique())
print('safety data is : ' , data['safety'].unique())
print('rating data is : ' , data['rating'].unique())

buying data is :  ['vhigh' 'high' 'med' 'low']
maint data is :  ['vhigh' 'high' 'med' 'low']
doors data is :  ['2' '3' '4' '5more']
persons data is :  ['2' '4' 'more']
lug_boot data is :  ['small' 'med' 'big']
safety data is :  ['low' 'med' 'high']
rating data is :  ['unacc' 'acc' 'vgood' 'good']

In [0]:
buying_mapping = {'vhigh': 0,'high': 1,'med': 2,'low': 3}
maint_mapping = {'vhigh': 0,'high': 1,'med': 2,'low': 3}
doors_mapping = {'2': 0,'3': 1,'4': 2,'5more': 3}
persons_mapping = {'2': 0,'4': 1,'more': 2}
lug_boot_mapping = {'small': 0,'med': 1,'big': 2}
safety_mapping = {'low': 0,'med': 1,'high': 2}
rating_mapping = {'unacc': 0,'acc': 1,'good': 2,'vgood': 3}

In [0]:
data['buying'] = data['buying'].map(buying_mapping)
data['maint'] = data['maint'].map(maint_mapping)
data['doors'] = data['doors'].map(doors_mapping)
data['persons'] = data['persons'].map(persons_mapping)
data['lug_boot'] = data['lug_boot'].map(lug_boot_mapping)
data['safety'] = data['safety'].map(safety_mapping)
data['rating'] = data['rating'].map(rating_mapping)

In [15]:
data.head(30)

    buying  maint  doors  persons  lug_boot  safety  rating
0        0      0      0        0         0       0       0
1        0      0      0        0         0       1       0
2        0      0      0        0         0       2       0
3        0      0      0        0         1       0       0
4        0      0      0        0         1       1       0
5        0      0      0        0         1       2       0
6        0      0      0        0         2       0       0
7        0      0      0        0         2       1       0
8        0      0      0        0         2       2       0
9        0      0      0        1         0       0       0
10       0      0      0        1         0       1       0
11       0      0      0        1         0       2       0
12       0      0      0        1         1       0       0
13       0      0      0        1         1       1       0
14       0      0      0        1         1       2       0
15       0      0      0        1         2       0       0
16       0      0      0        1         2       1       0
17       0      0      0        1         2       2       0
18       0      0      0        2         0       0       0
19       0      0      0        2         0       1       0
20       0      0      0        2         0       2       0
21       0      0      0        2         1       0       0
22       0      0      0        2         1       1       0
23       0      0      0        2         1       2       0
24       0      0      0        2         2       0       0
25       0      0      0        2         2       1       0
26       0      0      0        2         2       2       0
27       0      0      1        0         0       0       0
28       0      0      1        0         0       1       0
29       0      0      1        0         0       2       0

In [16]:
X_train, X_test, y_train, y_test = train_test_split(data[["buying", "maint", "doors", "persons", "lug_boot", "safety"]].values, data["rating"].values, random_state=42)

print('X_train shape is ' , X_train.shape)
print('X_test shape is ' , X_test.shape)
print('y_train shape is ' , y_train.shape)
print('y_test shape is ' , y_test.shape)

X_train shape is  (1296, 6)
X_test shape is  (432, 6)
y_train shape is  (1296,)
y_test shape is  (432,)

In [17]:
# Specify that all features have real-value data
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=6)]

# Build 3 layer DNN with 512, 256, 128 units respectively.
classifier = tf.contrib.learn.DNNClassifier(feature_columns=feature_columns,
                                            hidden_units=[512, 256, 128],
                                            n_classes=4,
                                            optimizer=tf.train.ProximalAdagradOptimizer(
                                                learning_rate=0.15,
                                                l1_regularization_strength=0.001
                                            ))

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/learn/python/learn/estimators/dnn.py:378: multi_class_head (from tensorflow.contrib.learn.python.learn.estimators.head) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.contrib.estimator.*_head.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/learn/python/learn/estimators/estimator.py:1180: BaseEstimator.__init__ (from tensorflow.contrib.learn.python.learn.estimators.estimator) is deprecated and will be removed in a future version.
Instructions for updating:
Please replace uses of any Estimator from tf.contrib.learn with an Estimator from tf.estimator.*
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/learn/python/learn/estimators/estimator.py:427: RunConfig.__init__ (from tensorflow.contrib.learn.python.learn.estimators.run_config) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpyejb8av6
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f097294e2e8>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute': None, '_eval_distribute': None, '_experimental_max_worker_delay_secs': None, '_device_fn': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_protocol': None, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/tmpyejb8av6', '_session_creation_timeout_secs': 7200}

In [0]:
# Define the training inputs
def get_train_inputs():
    x = tf.constant(X_train)
    y = tf.constant(y_train)
    return x, y

# Define the test inputs
def get_test_inputs():
    x = tf.constant(X_test)
    y = tf.constant(y_test)

    return x, y

In [19]:
# Fit model.
classifier.fit(input_fn=get_train_inputs, steps=1200)

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1866: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/learn/python/learn/estimators/head.py:678: ModelFnOps.__new__ (from tensorflow.contrib.learn.python.learn.estimators.model_fn) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.EstimatorSpec. You can use the `estimator_spec` method to create an equivalent one.
INFO:tensorflow:Create CheckpointSaverHook.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpyejb8av6/model.ckpt.
INFO:tensorflow:loss = 1.3852684, step = 1
INFO:tensorflow:global_step/sec: 32.2273
INFO:tensorflow:loss = 0.4932945, step = 101 (3.104 sec)
INFO:tensorflow:global_step/sec: 32.11
INFO:tensorflow:loss = 0.2778587, step = 201 (3.118 sec)
INFO:tensorflow:global_step/sec: 32.153
INFO:tensorflow:loss = 0.21135326, step = 301 (3.112 sec)
INFO:tensorflow:global_step/sec: 32.3313
INFO:tensorflow:loss = 0.1693799, step = 401 (3.088 sec)
INFO:tensorflow:global_step/sec: 32.2695
INFO:tensorflow:loss = 0.13201582, step = 501 (3.099 sec)
INFO:tensorflow:global_step/sec: 32.585
INFO:tensorflow:loss = 0.09859516, step = 601 (3.073 sec)
INFO:tensorflow:global_step/sec: 32.9007
INFO:tensorflow:loss = 0.116396256, step = 701 (3.039 sec)
INFO:tensorflow:global_step/sec: 32.6665
INFO:tensorflow:loss = 0.08153691, step = 801 (3.062 sec)
INFO:tensorflow:global_step/sec: 32.5171
INFO:tensorflow:loss = 0.07101968, step = 901 (3.072 sec)
INFO:tensorflow:global_step/sec: 32.6325
INFO:tensorflow:loss = 0.06316573, step = 1001 (3.068 sec)
INFO:tensorflow:global_step/sec: 32.9439
INFO:tensorflow:loss = 0.054165933, step = 1101 (3.035 sec)
INFO:tensorflow:Saving checkpoints for 1200 into /tmp/tmpyejb8av6/model.ckpt.
INFO:tensorflow:Loss for final step: 0.046348818.

DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x7f09775933c8>, 'hidden_units': [512, 256, 128], 'feature_columns': (_RealValuedColumn(column_name='', dimension=6, default_value=None, dtype=tf.float32, normalizer=None),), 'optimizer': <tensorflow.python.training.proximal_adagrad.ProximalAdagradOptimizer object at 0x7f09775784a8>, 'activation_fn': <function relu at 0x7f0988d44950>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [20]:
# Evaluate accuracy.
print(classifier.evaluate(input_fn=get_test_inputs, steps=1))

accuracy_score = classifier.evaluate(input_fn=get_test_inputs, steps=1)["accuracy"]
print("Test Accuracy: {0:f}".format(accuracy_score))

INFO:tensorflow:Starting evaluation at 2020-03-01T19:21:26Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpyejb8av6/model.ckpt-1200
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2020-03-01-19:21:27
INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.9837963, global_step = 1200, loss = 0.055989265
{'loss': 0.055989265, 'accuracy': 0.9837963, 'global_step': 1200}
INFO:tensorflow:Starting evaluation at 2020-03-01T19:21:27Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpyejb8av6/model.ckpt-1200
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2020-03-01-19:21:27
INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.9837963, global_step = 1200, loss = 0.055989265
Test Accuracy: 0.983796